export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
    { code: 'fr', name: 'Français', nativeName: 'Français', flag: '🇫🇷' },
    { code: 'en', name: 'Anglais', nativeName: 'English', flag: '🇬🇧' },
    { code: 'es', name: 'Espagnol', nativeName: 'Español', flag: '🇪🇸' },
    { code: 'de', name: 'Allemand', nativeName: 'Deutsch', flag: '🇩🇪' },
    { code: 'it', name: 'Italien', nativeName: 'Italiano', flag: '🇮🇹' },
    { code: 'pt', name: 'Portugais', nativeName: 'Português', flag: '🇵🇹' },
    { code: 'nl', name: 'Néerlandais', nativeName: 'Nederlands', flag: '🇳🇱' },
    { code: 'ru', name: 'Russe', nativeName: 'Русский', flag: '🇷🇺' },
    { code: 'ja', name: 'Japonais', nativeName: '日本語', flag: '🇯🇵' },
    { code: 'zh', name: 'Chinois', nativeName: '中文', flag: '🇨🇳' },
    { code: 'ar', name: 'Arabe', nativeName: 'العربية', flag: '🇸🇦' },
    { code: 'ko', name: 'Coréen', nativeName: '한국어', flag: '🇰🇷' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
    { code: 'sv', name: 'Suédois', nativeName: 'Svenska', flag: '🇸🇪' },
    { code: 'da', name: 'Danois', nativeName: 'Dansk', flag: '🇩🇰' },
    { code: 'fi', name: 'Finlandais', nativeName: 'Suomi', flag: '🇫🇮' },
    { code: 'no', name: 'Norvégien', nativeName: 'Norsk', flag: '🇳🇴' },
    { code: 'pl', name: 'Polonais', nativeName: 'Polski', flag: '🇵🇱' },
    { code: 'tr', name: 'Turc', nativeName: 'Türkçe', flag: '🇹🇷' },
    { code: 'el', name: 'Grec', nativeName: 'Ελληνικά', flag: '🇬🇷' },
    { code: 'he', name: 'Hébreu', nativeName: 'עברית', flag: '🇮🇱' },
    { code: 'id', name: 'Indonésien', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
    { code: 'th', name: 'Thaï', nativeName: 'ไทย', flag: '🇹🇭' },
    { code: 'vi', name: 'Vietnamien', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
    { code: 'cs', name: 'Tchèque', nativeName: 'Čeština', flag: '🇨🇿' },
    { code: 'hu', name: 'Hongrois', nativeName: 'Magyar', flag: '🇭🇺' },
    { code: 'ro', name: 'Roumain', nativeName: 'Română', flag: '🇷🇴' },
    { code: 'uk', name: 'Ukrainien', nativeName: 'Українська', flag: '🇺🇦' },
    { code: 'ta', name: 'Tamoul', nativeName: 'தமிழ்', flag: '🇱🇰' },
    { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦' },
    { code: 'sq', name: 'Albanais', nativeName: 'Shqip', flag: '🇦🇱' },
    { code: 'am', name: 'Amharique', nativeName: 'አማርኛ', flag: '🇪🇹' },
    { code: 'hy', name: 'Arménien', nativeName: 'Հայերեն', flag: '🇦🇲' },
    { code: 'az', name: 'Azéri', nativeName: 'Azərbaycan dili', flag: '🇦🇿' },
    { code: 'eu', name: 'Basque', nativeName: 'Euskara', flag: '🇪🇸' },
    { code: 'be', name: 'Biélorusse', nativeName: 'Беларуская', flag: '🇧🇾' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
    { code: 'bs', name: 'Bosniaque', nativeName: 'Bosanski', flag: '🇧🇦' },
    { code: 'bg', name: 'Bulgare', nativeName: 'Български', flag: '🇧🇬' },
    { code: 'ca', name: 'Catalan', nativeName: 'Català', flag: '🇪🇸' },
    { code: 'hr', name: 'Croate', nativeName: 'Hrvatski', flag: '🇭🇷' },
    { code: 'et', name: 'Estonien', nativeName: 'Eesti', flag: '🇪🇪' },
    { code: 'tl', name: 'Filipino', nativeName: 'Filipino', flag: '🇵🇭' },
    { code: 'gl', name: 'Galicien', nativeName: 'Galego', flag: '🇪🇸' },
    { code: 'ka', name: 'Géorgien', nativeName: 'ქართული', flag: '🇬🇪' },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
    { code: 'ha', name: 'Haoussa', nativeName: 'Hausa', flag: '🇳🇬' },
    { code: 'is', name: 'Islandais', nativeName: 'Íslenska', flag: '🇮🇸' },
    { code: 'ig', name: 'Igbo', nativeName: 'Igbo', flag: '🇳🇬' },
    { code: 'ga', name: 'Irlandais', nativeName: 'Gaeilge', flag: '🇮🇪' },
    { code: 'jv', name: 'Javanais', nativeName: 'Basa Jawa', flag: '🇮🇩' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
    { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі', flag: '🇰🇿' },
    { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', flag: '🇰🇭' },
    { code: 'ku', name: 'Kurde', nativeName: 'Kurdî', flag: '🇮🇶' },
    { code: 'ky', name: 'Kirghize', nativeName: 'Кыргызча', flag: '🇰🇬' },
    { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ', flag: '🇱🇦' },
    { code: 'lv', name: 'Letton', nativeName: 'Latviešu', flag: '🇱🇻' },
    { code: 'lt', name: 'Lituanien', nativeName: 'Lietuvių', flag: '🇱🇹' },
    { code: 'lb', name: 'Luxembourgeois', nativeName: 'Lëtzebuergesch', flag: '🇱🇺' },
    { code: 'mk', name: 'Macédonien', nativeName: 'Македонски', flag: '🇲🇰' },
    { code: 'mg', name: 'Malgache', nativeName: 'Malagasy', flag: '🇲🇬' },
    { code: 'ms', name: 'Malais', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
    { code: 'mt', name: 'Maltais', nativeName: 'Malti', flag: '🇲🇹' },
    { code: 'mi', name: 'Maori', nativeName: 'Te Reo Māori', flag: '🇳🇿' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
    { code: 'mn', name: 'Mongol', nativeName: 'Монгол', flag: '🇲🇳' },
    { code: 'my', name: 'Birman', nativeName: 'ဗမာစာ', flag: '🇲🇲' },
    { code: 'ne', name: 'Népalais', nativeName: 'नेपाली', flag: '🇳🇵' },
    { code: 'ps', name: 'Pachto', nativeName: 'پښتو', flag: '🇦🇫' },
    { code: 'fa', name: 'Perse', nativeName: 'فارسی', flag: '🇮🇷' },
    { code: 'pa', name: 'Pendjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
    { code: 'sr', name: 'Serbe', nativeName: 'Српски', flag: '🇷🇸' },
    { code: 'si', name: 'Cingalais', nativeName: 'සිංහල', flag: '🇱🇰' },
    { code: 'sk', name: 'Slovaque', nativeName: 'Slovenčina', flag: '🇸🇰' },
    { code: 'sl', name: 'Slovène', nativeName: 'Slovenščina', flag: '🇸🇮' },
    { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: '🇸🇴' },
    { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇹🇿' },
    { code: 'tg', name: 'Tadjik', nativeName: 'Тоҷикӣ', flag: '🇹🇯' },
    { code: 'te', name: 'Télougou', nativeName: 'తెలుగు', flag: '🇮🇳' },
    { code: 'ur', name: 'Ourdou', nativeName: 'اردو', flag: '🇵🇰' },
    { code: 'uz', name: 'Ouzbek', nativeName: 'Oʻzbekcha', flag: '🇺🇿' },
    { code: 'cy', name: 'Gallois', nativeName: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
    { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', flag: '🇿🇦' },
    { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', flag: '🇮🇱' },
    { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
    { code: 'zu', name: 'Zoulou', nativeName: 'isiZulu', flag: '🇿🇦' },
];
