export function BusinessPlanContent() {
    return (
      <div className="space-y-4 text-sm [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-6 [&_h2]:mb-2 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:mt-4 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2 [&_strong]:font-semibold">
          <p className="text-muted-foreground">This document provides a detailed explanation of what BookLine is, how the company will operate, and how it will generate revenue, based on the application's architecture and code.</p>
          
          <hr className="!my-6 border-border" />

          <h2>Our Vision for BookLine</h2>
          <p><strong>BookLine is a modern, specialized marketplace platform designed to directly connect ebook creators with readers.</strong> Our mission is to radically simplify publishing and monetization for authors, while offering buyers a rich and personalized discovery experience.</p>
          <p>We are not a publishing house, but a <strong>technology intermediary</strong>. We provide the tools, the storefront, and the secure infrastructure for transactions to occur with confidence.</p>

          <hr className="!my-6 border-border" />
          
          <h2>The Business Model: How BookLine Makes Money</h2>
          <p>Our revenue model is transparent and based on the success of the transactions that take place on our platform. It is broken down into two parts:</p>
          <ol className="list-decimal list-outside pl-5 space-y-4">
            <li>
                <strong>Seller-Side Commission:</strong> For each sale made, BookLine takes a <strong>fixed commission of €3.00</strong>. This commission allows us to cover payment processing fees, secure file hosting, and the continuous maintenance and improvement of our publishing tools.
                <ul className="!mt-2">
                    <li><strong>Concrete Example:</strong> If a seller prices their ebook at <strong>€20.00</strong>, their net gain on each sale will be <strong>€17.00</strong>.</li>
                </ul>
            </li>
            <li>
                <strong>Buyer-Side Service Fee:</strong> At the time of purchase, we add a <strong>fixed service fee of €3.50</strong> to the price of the ebook. These fees fund the development of the user experience, our AI recommendation tools, customer support, and platform security for buyers.
                <ul className="!mt-2">
                    <li><strong>Concrete Example:</strong> For the same €20.00 ebook, the final price paid by the buyer will be <strong>€23.50</strong>.</li>
                </ul>
            </li>
          </ol>
          <p>On each transaction, <strong>BookLine therefore generates a total revenue of €6.50</strong>. This model allows us to invest in the platform while ensuring that creators retain the vast majority of their earnings.</p>
          
          <hr className="!my-6 border-border" />

          <h2>How the Platform Works</h2>
          <h3>For Sellers (Creators):</h3>
          <ol className="list-decimal list-outside pl-5 space-y-2">
            <li><strong>Simplified Publishing:</strong> The seller uploads their ebook in PDF format. Our system <strong>automatically compresses and optimizes the file</strong> to reduce its size, improving the experience for the buyer without any visible loss of quality.</li>
            <li><strong>Listing for Sale:</strong> The seller provides the title, a compelling description, relevant keywords for discovery, and sets their selling price.</li>
            <li><strong>AI Analysis:</strong> This is one of our major assets. The seller has access to an analysis generated by artificial intelligence that suggests more relevant keywords and provides feedback to improve their description, thus maximizing their sales potential.</li>
            <li><strong>Performance Tracking:</strong> A dashboard allows the seller to track their sales statistics, generated revenue, and the performance of their publications.</li>
          </ol>

          <h3 className="!mt-6">For Buyers (Readers):</h3>
          <ol className="list-decimal list-outside pl-5 space-y-2">
            <li><strong>Personalized Profile Creation:</strong> Upon registration, the user chooses an avatar, a username, and most importantly, <strong>selects at least 5 interests</strong>. This is the core of our personalization system.</li>
            <li><strong>Intelligent Discovery:</strong>
                <ul className="!mt-2">
                    <li>On the homepage, the buyer sees ebook suggestions based on their interests.</li>
                    <li>Our search bar is powered by AI: it provides relevant search suggestions in real-time, even indicating how many publications match a keyword.</li>
                </ul>
            </li>
            <li><strong>Transparent Purchase:</strong> The purchasing process is clear, displaying the breakdown of the ebook price and service fees.</li>
            <li><strong>Personal Library:</strong> Once purchased, the ebook is added to the "Purchases" section of the user's profile, accessible at any time.</li>
            <li><strong>Integrated Reader:</strong> The user can read their ebooks directly on the platform thanks to an integrated PDF reader, optimized for mobile and desktop.</li>
          </ol>

          <hr className="!my-6 border-border" />

          <h2>What Makes Us Unique: Our Technology</h2>
          <ul className="!list-none !pl-0 space-y-2">
            <li><strong>Design and User Experience:</strong> We have developed a strong visual identity with a <strong>distorted glassmorphism effect</strong> applied across the entire interface. It's more than just a design; it's our signature.</li>
            <li><strong>Artificial Intelligence (via Genkit):</strong> AI is not a gimmick. It serves our users, whether it's helping sellers better market their work or helping buyers find that hidden gem.</li>
            <li><strong>Modern Tech Stack:</strong> The application is built on Next.js 14 (App Router), React, and TypeScript, ensuring a fast, robust, and scalable platform.</li>
            <li><strong>Internationalization:</strong> The platform is already set up to be used in French and English, and can easily be extended to other languages.</li>
          </ul>

          <p className="!mt-6">In summary, <strong>BookLine is not just a site for selling ebooks; it is an intelligent and well-designed ecosystem that values both the work of creators and the experience of readers.</strong></p>
      </div>
    )
}
